name: flutter_application_1
description: A new Flutter project.



version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.0.0

  english_words: ^4.0.0
  provider: ^6.0.0
  grpc: ^3.2.2
  fixnum: ^1.1.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  
